version: '3.8'

services:
  db:
    image: mysql:8
    container_name: research_due_diligence_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: research_due_diligence
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - research_network

  adminer:
    image: adminer
    container_name: research_due_diligence_adminer
    ports:
      - "8080:8080"
    networks:
      - research_network

  web:
    build: .
    container_name: research_due_diligence_web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code  # 映射当前文件夹到容器内的 /code 目录
    ports:
      - "8001:8000"
    depends_on:
      - db
    networks:
      - research_network

volumes:
  db_data:

networks:
  research_network:
